// *** Cutscene: Dragon's Eye entrance - Kelvor Domine appears ***

// visual effect at position -> Kelvor Domine appears -> Dialog starts
IF
  True()
THEN RESPONSE #100
  CutSceneId("A7KelvorEncounter")
  CreateCreature("cutspy", [855.736], 0)
  MoveViewPoint([830.754], VERY_FAST)
  Wait(1)
  CreateVisualEffect("a7ddoorh", [830.754])
  Wait(1)
  CreateCreature("a7ht01", [830.754], NW)
  Wait(1)
  ActionOverride("a7ht01", StartDialogueNoSet([PC]))
END
