// *** Default script for troll deaths ***

IF
  Die()
THEN RESPONSE #100
  CreateVisualEffectObject("ICMAGICH", Myself)
  CreateVisualEffectObject("SPFIREPI", Myself)
  DestroySelf()
END

IF
  OnCreation()
THEN RESPONSE #100
  StartTimer(77,6)
END

IF
  !StateCheck(Myself, STATE_REALLY_DEAD)
  HPLT(Myself, 12)
THEN RESPONSE #100
  StartTimer(77, 6)
  ChangeAnimationNoEffect("HGTRL02")
END

IF
  TimerExpired(77)
THEN RESPONSE #100
  StartTimer(77, 6)
END
