// *** Collection of macros and functions ***

// Sets the banter intervals for the PC to the specified value
DEFINE_ACTION_FUNCTION ~BanterAccelerator~
  INT_VAR
  pc_interval   = 3600    // PC banter interval (in seconds)
//  npc_interval  = (2 * pc_interval) - (pc_interval / 3)     // NPC banter interval (in seconds)
BEGIN
  COMPILE ~DjinniCompanion/scripts/a7afqtlk.baf~
    SET afq_banter_interval_pc  = pc_interval
//    SET afq_banter_interval_npc = npc_interval
    EVALUATE_BUFFER
END
